# Generated by Django 5.0.3 on 2024-03-17 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.FloatField(max_length=100, verbose_name='Цена')),
                ('is_published', models.BooleanField(default=True)),
                ('content', models.TextField(verbose_name='контент')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата добавление')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='moobile.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(blank=True, related_name='productstag', to='moobile.tag', verbose_name='Теги')),
            ],
        ),
        migrations.CreateModel(
            name='MobAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='Автор')),
                ('value', models.CharField(max_length=100, verbose_name='Книги')),
                ('nout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='moobile.product', verbose_name='новость')),
            ],
            options={
                'verbose_name': 'Техническая характеристка:',
                'verbose_name_plural': 'Технические характеристики:',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='mob_images/', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='moobile.product', verbose_name='Продукт')),
            ],
        ),
    ]
