# Generated by Django 5.0.3 on 2024-03-17 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moobile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MobAttribute',
            new_name='ProductAttribute',
        ),
    ]
