# Generated by Django 5.0.3 on 2024-03-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moobile', '0003_rename_title_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=100, verbose_name='Цена'),
        ),
    ]
