# Generated by Django 5.0.2 on 2024-04-16 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moobile', '0005_alter_productattribute_options_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='moobile.product'),
        ),
    ]
