# Generated by Django 5.0.2 on 2024-10-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moobile', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auth',
            field=models.CharField(default=1, max_length=100, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
